services:
  code-server:
    image: codercom/code-server:4.138.0
    network_mode: host
    environment:
      DOCKER_USER: ${USER}
    user: "${UID}:${GID}"
    volumes:
      - ./dot-config/code-server:${HOME}/.config/code-server
      - ./exp/code-server/.local/share/code-server:${HOME}/.local/share/code-server
      - ${HOME}/git:${HOME}/git:ro
    command:
      - --bind-addr
      - 0.0.0.0:9620
      - --config
      - ${HOME}/.config/code-server/config.yaml
      - --user-data-dir
      - ${HOME}/.local/share/code-server